dependencies:
  - name: "prometheus-operator"
    version: 5.14.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "fluentd-cloudwatch"
    version: 0.6.4
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: global.runningOnAws
  - name: "concourse"
    version: 6.4.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "kiam"
    version: 2.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: global.runningOnAws
  - name: "harbor"
    version: 1.1.0
    repository: https://helm.goharbor.io/
