global:
  account:
    name: "local"
  cluster:
    domain: "local.govsandbox.uk"
  mtls:
    enabled: false

concourse:
  concourse:
    web:
      externalUrl: "http://ci.local.govsandbox.uk"
  worker:
    persistence:
      enabled: false
    replicas: 1
  postgresql:
    persistence:
      enabled: false

harbor:
  expose:
    type: ingress
    tls:
      enabled: false
    ingress:
      hosts:
        core: registry.local.govsandbox.uk
  externalURL: http://registry.local.govsandbox.uk
