global:
  account:
    name: "local"
  cluster:
    domain: "local.govsandbox.uk"
  mtls:
    enabled: true
  concourse:
    enabled: false
  harbor:
    enabled: false

namespaces: []

googleOauthClientId: "foo"
googleOauthClientSecret: "bar"

concourse:
  concourse:
    web:
      externalUrl: "http://ci.local.govsandbox.uk"
  worker:
    persistence:
      enabled: false
    replicas: 1
  postgresql:
    persistence:
      enabled: false

harbor:
  expose:
    type: ingress
    tls:
      enabled: false
    ingress:
      hosts:
        core: registry.local.govsandbox.uk
  externalURL: http://registry.local.govsandbox.uk

gatekeeper:
  enabled: false

gsp-monitoring:
  prometheus-operator:
    prometheus:
      prometheusSpec:
        # This following doesn't do what I'd expect (remove the `storageSpec`
        # key from the merged output). I think because of this bug:
        # https://github.com/helm/helm/pull/6080. The fix is merged but is not
        # part of any release of Helm 2.x. This will probably only by a problem
        # if running GSP local. In this case you should delete the PVC from
        # your source tree locally.
        storageSpec: null
        replicas: 1
    grafana:
      persistence:
        enabled: false
      env:
        GF_AUTH_GOOGLE_ENABLED: "false"

istio:
  galley:
    replicaCount: 1
  certmanager:
    replicaCount: 1
  mixer:
    policy:
      replicaCount: 1
      autoscaleMin: 1
    telemetry:
      replicaCount: 1
      autoscaleMin: 1
  pilot:
    replicaCount: 1
    autoscaleMin: 1
  sidecarInjectorWebhook:
    replicaCount: 1
