---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-viewer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["list", "get", "watch"]
- nonResourceURLs: ["*"]
  verbs: ["list", "get"]
- apiGroups: ["verify.govsvc.uk"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
