---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sealed-secrets-controller
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sealed-secrets-controller
spec:
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-sealed-secrets-controller
    spec:
      containers:
      - command:
        - controller
        {{ if .Values.global.runningOnAws }}
        args:
        - "--key-name={{ .Release.Name }}-sealed-secrets-key"
        {{ end }}
        image: quay.io/bitnami/sealed-secrets-controller:v0.7.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        name: sealed-secrets-controller
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
      serviceAccountName: {{ .Release.Name }}-sealed-secrets-controller
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sealed-secrets-controller
spec:
  ports:
  - port: 8080
  selector:
    name: {{ .Release.Name }}-sealed-secrets-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-sealed-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-sealed-secrets-key-admin
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ .Release.Name }}-sealed-secrets-controller
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ .Release.Name }}-sealed-secrets-key-admin
rules:
- apiGroups:
  - ""
  resourceNames:
  {{ if .Values.global.runningOnAws }}
  - {{ .Release.Name }}-sealed-secrets-key
  {{ else }}
  - sealed-secrets-key
  {{ end }}
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-sealed-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-secrets-unsealer
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ .Release.Name }}-sealed-secrets-controller
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-secrets-unsealer
rules:
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - delete
